# Tensorflow - Sintaxis básica

In [14]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [15]:
mensaje1 = tf.constant("Hola ")
mensaje2 = tf.constant("mundo")

In [16]:
print(mensaje1)

Tensor("Const:0", shape=(), dtype=string)


In [17]:
type(mensaje1)

tensorflow.python.framework.ops.Tensor

In [18]:
with tf.Session() as sesion:
    resultado = sesion.run(mensaje1 + mensaje2)

In [19]:
resultado

b'Hola mundo'

In [20]:
a = tf.constant(10)
b = tf.constant(5)

In [21]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [22]:
with tf.Session() as sesion:
    resultado = sesion.run(a + b)

In [23]:
resultado

15

In [24]:
constante = tf.constant(15)
matriz1 = tf.fill((6,6),10)

In [25]:
matriz2 = tf.random_normal((5,5))

In [26]:
matriz3 = tf.random_uniform((4,4),minval=0,maxval=4)

In [27]:
matriz_ceros = tf.zeros((2,2))

In [31]:
matriz_unos = tf.ones((3,3))

In [33]:
operaciones = [constante,matriz1,matriz2,matriz3, matriz_ceros, matriz_unos]

In [34]:
with tf.Session() as sesion:
    for op in operaciones:
        print(sesion.run(op))
        print("\n")

15


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


[[-1.3274513   0.36206418  0.25568372 -0.7222088  -0.83879465]
 [-0.69988805  0.19850661 -1.9003433  -0.8443697   0.6570707 ]
 [-0.26151475  0.45648322 -0.6192037  -1.6984327  -0.8990977 ]
 [-0.42857486  0.45586985 -0.32482782 -1.3849947  -0.18877801]
 [ 0.82533157 -0.39020684 -0.71767473  1.0205693   1.6424766 ]]


[[2.7783608  3.5750337  0.10382318 3.176094  ]
 [0.8652668  0.8453045  3.1746945  1.3549604 ]
 [1.7722716  1.1764183  0.74426603 2.3387446 ]
 [2.6353836  1.874886   0.86167336 3.6151056 ]]


[[0. 0.]
 [0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


