# Grafos en Tensorflow

In [1]:
import tensorflow as tf

In [2]:
nodo1 = tf.constant(4)
nodo2 = tf.constant(6)

In [3]:
nodo3 = nodo1 + nodo2

In [4]:
print(nodo3)

Tensor("add:0", shape=(), dtype=int32)


In [5]:
with tf.Session() as sesion:
    resultado = sesion.run(nodo3)

In [6]:
print(resultado)

10


# Grafos por defecto

In [7]:
print(tf.get_default_graph())

In [8]:
grafo1 = tf.Graph()
print(grafo1)

In [9]:
with grafo1.as_default():
    print(grafo1 is tf.get_default_graph())

True


In [10]:
 print(grafo1 is tf.get_default_graph())

False


# Variables y placeholders

In [11]:
tensor = tf.random_uniform((5,5),0,1)

In [12]:
variable = tf.Variable(initial_value= tensor)

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
print(variable)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32_ref>


In [14]:
inicializador = tf.global_variables_initializer()

In [17]:
with tf.Session() as sesion:
    sesion.run(inicializador)
    resultado = sesion.run(variable)

In [19]:
print(resultado)

[[0.47900045 0.39157665 0.00402689 0.42166543 0.08256662]
 [0.33894885 0.97890234 0.1444484  0.4785912  0.9400573 ]
 [0.75601804 0.48933363 0.78364754 0.86716866 0.73090065]
 [0.91423    0.20199335 0.23604333 0.75181305 0.34644127]
 [0.47120976 0.2230326  0.37707996 0.9171189  0.28959394]]


In [20]:
## Los placeholders se utilizan para alimentar los ejemplos de entrenamiento del modelo.

In [21]:
incognitas = tf.placeholder(tf.float32,shape=(20,20))

In [22]:
print(incognitas)

Tensor("Placeholder:0", shape=(20, 20), dtype=float32)
