# Regresión con Tensorflow

In [1]:
import pandas as pd
import tensorflow as tf

In [3]:
# Usamos el dataset de https://www.kaggle.com/camnugent/california-housing-prices

In [2]:
casas = pd.read_csv('precios-casas.csv')
casas.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [4]:
casas_x = casas.drop('median_house_value',axis=1)
casas_x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [5]:
casas_y = casas['median_house_value']
casas_y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(casas_x,casas_y,test_size=0.3)

In [9]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
11782    -121.32     38.03                25.0       2474.0           513.0   
15149    -122.26     37.77                52.0       2097.0           444.0   
12837    -121.82     39.73                33.0       2242.0           517.0   
10424    -120.27     37.12                36.0       1219.0           258.0   
908      -117.08     32.69                36.0       1571.0           284.0   

       population  households  median_income  
11782      1947.0       524.0         2.5742  
15149       915.0       413.0         2.9899  
12837      1160.0       449.0         1.7426  
10424       639.0       245.0         1.9464  
908        1001.0       268.0         3.6875

# Normalizar

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
normalizador = MinMaxScaler()

In [14]:
normalizador.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [15]:
x_train = pd.DataFrame(data=normalizador.transform(x_train), columns=x_train.columns,index=x_train.index)

In [16]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
11782   0.301793  0.583422            0.470588     0.065164        0.093436   
15149   0.208167  0.555792            1.000000     0.055226        0.080819   
12837   0.251992  0.764081            0.627451     0.059048        0.094167   
10424   0.406375  0.486716            0.686275     0.032081        0.046809   
908     0.724104  0.015940            0.686275     0.041360        0.051563   

       population  households  median_income  
11782    0.054486    0.100636       0.143053  
15149    0.025561    0.079237       0.171722  
12837    0.032428    0.086177       0.085702  
10424    0.017826    0.046848       0.099757  
908      0.027972    0.051282       0.219831

In [17]:
x_test =  pd.DataFrame(data=normalizador.transform(x_test), columns=x_test.columns,index=x_test.index)

In [18]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12170   0.288845  0.636557            0.647059     0.045209        0.064363   
16105   0.188247  0.556854            1.000000     0.109081        0.179558   
5716    0.613546  0.165781            0.803922     0.041518        0.068934   
9423    0.509960  0.183847            0.549020     0.086885        0.146645   
14459   0.221116  0.522848            0.666667     0.034770        0.054489   

       population  households  median_income  
12170    0.023683    0.058608       0.136150  
16105    0.056812    0.171583       0.201632  
5716     0.036828    0.072489       0.187046  
9423     0.042210    0.136688       0.228452  
14459    0.031671    0.054945       0.222845

In [22]:
#crear variables con los valores numericos para las categorias. La columna objetivo NO

In [20]:
casas.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [23]:
longitude = tf.feature_column.numeric_column('longitude')
latitude = tf.feature_column.numeric_column('latitude')
housing_median_age = tf.feature_column.numeric_column('housing_median_age')
total_rooms = tf.feature_column.numeric_column('total_rooms')
total_bedrooms = tf.feature_column.numeric_column('total_bedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
median_income = tf.feature_column.numeric_column('median_income')
median_income = tf.feature_column.numeric_column('median_income')

In [28]:
columnas = [longitude, latitude, housing_median_age, total_rooms,total_bedrooms, population, households, median_income]

In [29]:
columnas

[NumericColumn(key='longitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='latitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='housing_median_age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='total_rooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='total_bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='population', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='households', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='median_income', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [30]:
#Funcion de entrada

In [31]:
funcion_entrada = tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=10, num_epochs=1000,shuffle=True)

In [32]:
#Creamos el modelo

In [33]:
modelo = tf.estimator.DNNRegressor(hidden_units=[10,10,10], feature_columns=columnas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\sysadmin\\AppData\\Local\\Temp\\tmp28eyz61o', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000049105DB940>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [34]:
#entrenamos el modelo

In [35]:
modelo.train(input_fn=funcion_entrada,steps=8000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\sysadmin\AppData\Local\Temp\tmp28eyz61o\model.ckpt.
INFO:tensorflow:loss = 753806500000.0, step = 1
INFO:tensorflow:global_step/sec: 205.18
INFO:tensorflow:loss = 433994560000.0, step = 101 (0.497 sec)
INFO:tensorflow:global_step/sec: 398.622
INFO:tensorflow:loss = 605847300000.0, step = 201 (0.241 sec)
INFO:tensorflow:global_step/sec: 4

INFO:tensorflow:loss = 92905210000.0, step = 5901 (0.262 sec)
INFO:tensorflow:global_step/sec: 343.258
INFO:tensorflow:loss = 145997510000.0, step = 6001 (0.288 sec)
INFO:tensorflow:global_step/sec: 398.786
INFO:tensorflow:loss = 126200996000.0, step = 6101 (0.251 sec)
INFO:tensorflow:global_step/sec: 370.947
INFO:tensorflow:loss = 92953534000.0, step = 6201 (0.272 sec)
INFO:tensorflow:global_step/sec: 371.155
INFO:tensorflow:loss = 60017930000.0, step = 6301 (0.267 sec)
INFO:tensorflow:global_step/sec: 352.96
INFO:tensorflow:loss = 102328975000.0, step = 6401 (0.282 sec)
INFO:tensorflow:global_step/sec: 352.959
INFO:tensorflow:loss = 73665340000.0, step = 6501 (0.283 sec)
INFO:tensorflow:global_step/sec: 370.395
INFO:tensorflow:loss = 100455770000.0, step = 6601 (0.271 sec)
INFO:tensorflow:global_step/sec: 369.433
INFO:tensorflow:loss = 80836035000.0, step = 6701 (0.271 sec)
INFO:tensorflow:global_step/sec: 403.618
INFO:tensorflow:loss = 152946820000.0, step = 6801 (0.261 sec)
INFO:te

In [36]:
#Una vez entrenado, creamos las predicciones

In [37]:
funcion_entrada_prediccion = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=10, num_epochs=1, shuffle=False)

In [38]:
generador_predicciones = modelo.predict(funcion_entrada_prediccion)

In [39]:
predicciones = list(generador_predicciones)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\sysadmin\AppData\Local\Temp\tmp28eyz61o\model.ckpt-8000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [40]:
predicciones

[{'predictions': array([193889.3], dtype=float32)},
 {'predictions': array([242312.88], dtype=float32)},
 {'predictions': array([219116.67], dtype=float32)},
 {'predictions': array([212914.14], dtype=float32)},
 {'predictions': array([199717.47], dtype=float32)},
 {'predictions': array([187536.44], dtype=float32)},
 {'predictions': array([216679.73], dtype=float32)},
 {'predictions': array([271423.03], dtype=float32)},
 {'predictions': array([181506.42], dtype=float32)},
 {'predictions': array([218120.42], dtype=float32)},
 {'predictions': array([216916.27], dtype=float32)},
 {'predictions': array([173780.3], dtype=float32)},
 {'predictions': array([229391.77], dtype=float32)},
 {'predictions': array([192942.16], dtype=float32)},
 {'predictions': array([165867.95], dtype=float32)},
 {'predictions': array([217405.05], dtype=float32)},
 {'predictions': array([191060.45], dtype=float32)},
 {'predictions': array([199302.86], dtype=float32)},
 {'predictions': array([209640.55], dtype=float3

In [41]:
#recogemos los valores de los precios medios de las casas

In [42]:
predicciones_finales = []
for prediccion in predicciones:
    predicciones_finales.append(prediccion['predictions'])

In [43]:
predicciones_finales

[array([193889.3], dtype=float32),
 array([242312.88], dtype=float32),
 array([219116.67], dtype=float32),
 array([212914.14], dtype=float32),
 array([199717.47], dtype=float32),
 array([187536.44], dtype=float32),
 array([216679.73], dtype=float32),
 array([271423.03], dtype=float32),
 array([181506.42], dtype=float32),
 array([218120.42], dtype=float32),
 array([216916.27], dtype=float32),
 array([173780.3], dtype=float32),
 array([229391.77], dtype=float32),
 array([192942.16], dtype=float32),
 array([165867.95], dtype=float32),
 array([217405.05], dtype=float32),
 array([191060.45], dtype=float32),
 array([199302.86], dtype=float32),
 array([209640.55], dtype=float32),
 array([229049.45], dtype=float32),
 array([333294.1], dtype=float32),
 array([194914.3], dtype=float32),
 array([226553.78], dtype=float32),
 array([182849.84], dtype=float32),
 array([214490.33], dtype=float32),
 array([205742.52], dtype=float32),
 array([204768.77], dtype=float32),
 array([183706.44], dtype=float3

In [44]:
#calculamos el error cuadratico medio para ver el error

In [45]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test,pred)