# Redes neuronales con tensorflow

<img src="nna.jpg">

In [6]:
import tensorflow as tf
import numpy as np

In [7]:
aleatorio_a = np.random.uniform(0,50,(4,4))

In [8]:
aleatorio_a

array([[44.97435024, 15.12385583, 10.91521937, 20.24759105],
       [23.08109057, 10.69253361, 16.10126675, 26.1039303 ],
       [42.75047735, 44.88956904,  0.66152264,  7.34008204],
       [25.90299784, 46.70341829, 22.0332798 ,  1.58911728]])

In [9]:
aleatorio_b = np.random.uniform(0,50,(4,1))

In [10]:
aleatorio_b

array([[26.5272418 ],
       [43.79723904],
       [ 8.45356421],
       [ 2.07850845]])

In [11]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [12]:
suma = a + b
multiplicacion = a * b

In [15]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma,feed_dict={a:10, b:20})
    print(resultado_suma)

30.0


In [16]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma,feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_suma)

[[71.501595  41.6511    37.442463  46.774834 ]
 [66.87833   54.48977   59.898506  69.90117  ]
 [51.20404   53.343132   9.1150875 15.793647 ]
 [27.981506  48.78193   24.111788   3.6676257]]


In [17]:
with tf.Session() as sesion:
    resultado_multi = sesion.run(multiplicacion,feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_multi)

[[1193.0455     401.19418    289.55066    537.11273  ]
 [1010.888      468.30344    705.191     1143.28     ]
 [ 361.39392    379.47687      5.592224    62.04986  ]
 [  53.8396      97.07345     45.796356     3.3029935]]


In [18]:
with tf.Session() as sesion:
    resultado_multi = sesion.run(multiplicacion,feed_dict={a:10, b:20})
    print(resultado_multi)

200.0


-------------------

In [19]:
#Ejemplo:

In [20]:
caracteristicas = 10
neuronas = 4

In [34]:
# Wx +b

In [21]:
x = tf.placeholder(tf.float32,(None,caracteristicas))

In [23]:
W = tf.Variable(tf.random.normal([caracteristicas,neuronas]))

Instructions for updating:
Colocations handled automatically by placer.


In [24]:
b = tf.Variable(tf.ones([neuronas]))

In [25]:
multiplicacion = tf.matmul(x,W)

In [35]:
z_lineal = tf.add(multiplicacion,b)

In [27]:
z_nolineal = tf.sigmoid(z)

In [28]:
inicializacion = tf.global_variables_initializer()

In [29]:
valores_x = np.random.random([1,caracteristicas])

In [30]:
valores_x

array([[0.91310036, 0.50966755, 0.56213193, 0.08242081, 0.05543895,
        0.90895712, 0.56077155, 0.47187292, 0.0764853 , 0.57347871]])

In [31]:
with tf.Session() as sesion:
    sesion.run(inicializacion)
    resultado = sesion.run(z_nolineal, feed_dict={x:valores_x})

In [32]:
print(resultado)

[[0.9514768  0.33131236 0.91710305 0.99836886]]
