# Regresión con Tensorflow

In [5]:
import pandas as pd
import tensorflow as tf

In [6]:
# Usamos el dataset de https://www.kaggle.com/camnugent/california-housing-prices

In [7]:
casas = pd.read_csv('precios-casas.csv')
casas.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [8]:
casas_x = casas.drop('median_house_value',axis=1)
casas_x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [9]:
casas_y = casas['median_house_value']
casas_y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(casas_x,casas_y,test_size=0.3)

In [12]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
9272    -119.11     35.42                52.0        154.0            28.0   
674     -117.04     32.62                27.0       1710.0           282.0   
6623    -118.28     33.96                37.0       1812.0           500.0   
7057    -118.32     34.13                34.0       1856.0           273.0   
6468    -118.27     34.07                33.0       1177.0           468.0   

      population  households  median_income  
9272        37.0        16.0        10.0263  
674       1089.0       297.0         4.6793  
6623      1640.0       447.0         1.9348  
7057       540.0       264.0         4.0833  
6468      1533.0       430.0         2.3981

# Normalizar

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
normalizador = MinMaxScaler()

In [15]:
normalizador.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [16]:
x_train = pd.DataFrame(data=normalizador.transform(x_train), columns=x_train.columns,index=x_train.index)

In [17]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
9272   0.527976  0.306057            1.000000     0.004476        0.004190   
674    0.738555  0.008502            0.509804     0.052178        0.043606   
6623   0.612411  0.150903            0.705882     0.055305        0.077436   
7057   0.608342  0.168969            0.647059     0.056654        0.042210   
6468   0.613428  0.162593            0.627451     0.035838        0.072471   

      population  households  median_income  
9272    0.001190    0.002467       0.656984  
674     0.038021    0.048676       0.288231  
6623    0.057312    0.073343       0.098957  
7057    0.018801    0.043249       0.247128  
6468    0.053566    0.070548       0.130909

In [18]:
x_test =  pd.DataFrame(data=normalizador.transform(x_test), columns=x_test.columns,index=x_test.index)

In [19]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
10945   0.348932  0.481403            0.490196     0.062172        0.062073   
2813    0.669379  0.162593            0.627451     0.125448        0.114680   
4383    0.638861  0.132837            0.431373     0.194978        0.159683   
8942    0.551373  0.184910            0.411765     0.103038        0.119491   
13540   0.237030  0.616366            0.294118     0.071216        0.069677   

       population  households  median_income  
10945    0.046914    0.067916       0.216080  
2813     0.090222    0.119882       0.222907  
4383     0.114764    0.164447       0.387188  
8942     0.096208    0.116593       0.244652  
13540    0.037496    0.065614       0.243652

In [20]:
#crear variables con los valores numericos para las categorias. La columna objetivo NO

In [21]:
casas.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [22]:
longitude = tf.feature_column.numeric_column('longitude')
latitude = tf.feature_column.numeric_column('latitude')
housing_median_age = tf.feature_column.numeric_column('housing_median_age')
total_rooms = tf.feature_column.numeric_column('total_rooms')
total_bedrooms = tf.feature_column.numeric_column('total_bedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
median_income = tf.feature_column.numeric_column('median_income')
median_income = tf.feature_column.numeric_column('median_income')

In [23]:
columnas = [longitude, latitude, housing_median_age, total_rooms,total_bedrooms, population, households, median_income]

In [24]:
columnas

[NumericColumn(key='longitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='latitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='housing_median_age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='total_rooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='total_bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='population', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='households', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='median_income', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [25]:
#Funcion de entrada

In [26]:
funcion_entrada = tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=10, num_epochs=1000,shuffle=True)

In [27]:
#Creamos el modelo

In [28]:
modelo = tf.estimator.DNNRegressor(hidden_units=[10,10,10], feature_columns=columnas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\sysadmin\\AppData\\Local\\Temp\\tmpuovtokeg', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000601EB850B8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [34]:
#entrenamos el modelo

In [29]:
modelo.train(input_fn=funcion_entrada,steps=8000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\sysadmin\AppData\Local\Temp\tmpuovtokeg\model.ckpt.
INFO:tensorflow:loss = 861768250000.0, step = 1
INFO:tensorflow:global_step/sec: 204.891
INFO:tensorflow:loss = 616644900000.0, step = 101 (0.497 sec)
INFO:tensorflow:global_step/sec: 424.215
INFO:tensorflow:loss = 719905500000.0, step = 201 (0.227 sec)
INFO:tensorflow:global_step/sec: 

INFO:tensorflow:global_step/sec: 325.977
INFO:tensorflow:loss = 46877135000.0, step = 5901 (0.291 sec)
INFO:tensorflow:global_step/sec: 303.917
INFO:tensorflow:loss = 51171516000.0, step = 6001 (0.337 sec)
INFO:tensorflow:global_step/sec: 289.525
INFO:tensorflow:loss = 76260670000.0, step = 6101 (0.346 sec)
INFO:tensorflow:global_step/sec: 307.144
INFO:tensorflow:loss = 122447225000.0, step = 6201 (0.322 sec)
INFO:tensorflow:global_step/sec: 360.607
INFO:tensorflow:loss = 51279864000.0, step = 6301 (0.279 sec)
INFO:tensorflow:global_step/sec: 436.19
INFO:tensorflow:loss = 100831840000.0, step = 6401 (0.229 sec)
INFO:tensorflow:global_step/sec: 443.945
INFO:tensorflow:loss = 129179705000.0, step = 6501 (0.224 sec)
INFO:tensorflow:global_step/sec: 441.924
INFO:tensorflow:loss = 177182570000.0, step = 6601 (0.226 sec)
INFO:tensorflow:global_step/sec: 446.307
INFO:tensorflow:loss = 83368985000.0, step = 6701 (0.222 sec)
INFO:tensorflow:global_step/sec: 439.896
INFO:tensorflow:loss = 666634

In [36]:
#Una vez entrenado, creamos las predicciones

In [37]:
funcion_entrada_prediccion = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=10, num_epochs=1, shuffle=False)

In [38]:
generador_predicciones = modelo.predict(funcion_entrada_prediccion)

In [39]:
predicciones = list(generador_predicciones)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\sysadmin\AppData\Local\Temp\tmpuovtokeg\model.ckpt-8000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [40]:
predicciones

[{'predictions': array([200098.7], dtype=float32)},
 {'predictions': array([231916.36], dtype=float32)},
 {'predictions': array([246691.92], dtype=float32)},
 {'predictions': array([210137.58], dtype=float32)},
 {'predictions': array([188092.39], dtype=float32)},
 {'predictions': array([204236.7], dtype=float32)},
 {'predictions': array([196489.02], dtype=float32)},
 {'predictions': array([209024.86], dtype=float32)},
 {'predictions': array([204699.11], dtype=float32)},
 {'predictions': array([252813.44], dtype=float32)},
 {'predictions': array([189018.69], dtype=float32)},
 {'predictions': array([245468.31], dtype=float32)},
 {'predictions': array([200029.45], dtype=float32)},
 {'predictions': array([266184.3], dtype=float32)},
 {'predictions': array([169706.52], dtype=float32)},
 {'predictions': array([201488.08], dtype=float32)},
 {'predictions': array([229558.77], dtype=float32)},
 {'predictions': array([205573.86], dtype=float32)},
 {'predictions': array([202825.77], dtype=float32

In [30]:
#recogemos los valores de los precios medios de las casas

In [41]:
predicciones_finales = []
for prediccion in predicciones:
    predicciones_finales.append(prediccion['predictions'])

In [42]:
predicciones_finales

[array([200098.7], dtype=float32),
 array([231916.36], dtype=float32),
 array([246691.92], dtype=float32),
 array([210137.58], dtype=float32),
 array([188092.39], dtype=float32),
 array([204236.7], dtype=float32),
 array([196489.02], dtype=float32),
 array([209024.86], dtype=float32),
 array([204699.11], dtype=float32),
 array([252813.44], dtype=float32),
 array([189018.69], dtype=float32),
 array([245468.31], dtype=float32),
 array([200029.45], dtype=float32),
 array([266184.3], dtype=float32),
 array([169706.52], dtype=float32),
 array([201488.08], dtype=float32),
 array([229558.77], dtype=float32),
 array([205573.86], dtype=float32),
 array([202825.77], dtype=float32),
 array([197268.3], dtype=float32),
 array([217913.89], dtype=float32),
 array([223095.33], dtype=float32),
 array([178347.97], dtype=float32),
 array([184218.42], dtype=float32),
 array([211089.58], dtype=float32),
 array([261400.77], dtype=float32),
 array([244286.36], dtype=float32),
 array([208518.1], dtype=float32

In [44]:
#calculamos el error cuadratico medio para ver el error

In [43]:
from sklearn.metrics import mean_squared_error

In [44]:
mean_squared_error(y_test,predicciones_finales)**0.5

105589.06440722791